# Generated by Django 4.0.4 on 2022-05-15 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Proprietaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('prenom', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('num_phone', models.IntegerField()),
                ('Adresse', models.CharField(max_length=200)),
                ('photo', models.ImageField(upload_to='photos=%Y/%m/%d/')),
                ('is_vet', models.BooleanField(default=False)),
            ],
        ),
    ]
