# Generated by Django 4.0.4 on 2022-05-16 13:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('proprietaires', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='proprietaire',
            old_name='Adresse',
            new_name='adresse',
        ),
    ]
