# Generated by Django 4.0.4 on 2022-05-15 16:33

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('proprietaires', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CalVac',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_vac', models.DateTimeField()),
                ('daterappel_vac', models.DateTimeField()),
                ('vaccin', models.CharField(max_length=200)),
                ('observations', models.CharField(max_length=200)),
                ('praticien', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Consultation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_cons', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('prix', models.DecimalField(decimal_places=2, max_digits=3)),
                ('Note', models.CharField(max_length=200)),
                ('poids_cons', models.DecimalField(decimal_places=3, max_digits=3)),
                ('taille_cons', models.DecimalField(decimal_places=2, max_digits=2)),
            ],
        ),
        migrations.CreateModel(
            name='Carnet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('espece', models.CharField(max_length=100)),
                ('race', models.CharField(max_length=100)),
                ('sexe', models.CharField(max_length=100)),
                ('couleur', models.CharField(max_length=100)),
                ('pedigre', models.BooleanField(default=True)),
                ('sterilise', models.BooleanField(default=True)),
                ('num_id', models.CharField(max_length=200)),
                ('type_id', models.CharField(max_length=200)),
                ('place_id', models.CharField(max_length=200)),
                ('date_nais', models.DateTimeField()),
                ('poids_nais', models.DecimalField(decimal_places=3, max_digits=3)),
                ('taille_nais', models.DecimalField(decimal_places=2, max_digits=2)),
                ('lieu_nais', models.CharField(max_length=200)),
                ('date_arrive', models.DateTimeField()),
                ('poids_arrive', models.DecimalField(decimal_places=3, max_digits=3)),
                ('taille_arrive', models.DecimalField(decimal_places=2, max_digits=2)),
                ('eleveur', models.CharField(max_length=200)),
                ('date_depart', models.CharField(max_length=200)),
                ('poids_depart', models.DecimalField(decimal_places=3, max_digits=3)),
                ('taille_depart', models.DecimalField(decimal_places=2, max_digits=2)),
                ('type', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('comportement', models.TextField(blank=True)),
                ('antecedants', models.TextField(blank=True)),
                ('assurance', models.TextField(blank=True)),
                ('photo_main', models.ImageField(blank=True, upload_to='photos/%Y/%m/%d/')),
                ('proprietaire', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='proprietaires.proprietaire')),
            ],
        ),
    ]
