# Generated by Django 4.0.4 on 2022-05-16 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carnets', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carnet',
            name='date_arrive',
        ),
        migrations.RemoveField(
            model_name='carnet',
            name='date_depart',
        ),
        migrations.RemoveField(
            model_name='carnet',
            name='eleveur',
        ),
        migrations.RemoveField(
            model_name='carnet',
            name='poids_arrive',
        ),
        migrations.RemoveField(
            model_name='carnet',
            name='poids_depart',
        ),
        migrations.RemoveField(
            model_name='carnet',
            name='taille_arrive',
        ),
        migrations.RemoveField(
            model_name='carnet',
            name='taille_depart',
        ),
        migrations.RemoveField(
            model_name='carnet',
            name='type',
        ),
        migrations.AlterField(
            model_name='carnet',
            name='taille_nais',
            field=models.DecimalField(decimal_places=3, max_digits=3),
        ),
    ]
