# Generated by Django 4.0.4 on 2022-05-16 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carnets', '0002_remove_carnet_date_arrive_remove_carnet_date_depart_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carnet',
            name='taille_nais',
            field=models.DecimalField(decimal_places=2, max_digits=4),
        ),
    ]
