# Generated by Django 4.0.4 on 2022-05-24 15:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('carnets', '0003_alter_carnet_taille_nais'),
    ]

    operations = [
        migrations.RenameField(
            model_name='consultation',
            old_name='Note',
            new_name='note',
        ),
        migrations.AddField(
            model_name='consultation',
            name='nom',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.DO_NOTHING, to='carnets.carnet'),
            preserve_default=False,
        ),
    ]
