# Generated by Django 4.0.4 on 2022-05-24 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carnets', '0004_rename_note_consultation_note_consultation_nom'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consultation',
            name='poids_cons',
            field=models.DecimalField(decimal_places=3, max_digits=6),
        ),
        migrations.AlterField(
            model_name='consultation',
            name='prix',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
        migrations.AlterField(
            model_name='consultation',
            name='taille_cons',
            field=models.DecimalField(decimal_places=2, max_digits=4),
        ),
    ]
