# Generated by Django 4.0.4 on 2022-05-25 23:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carnets', '0006_calvac_nom'),
    ]

    operations = [
        migrations.AddField(
            model_name='carnet',
            name='photo_1',
            field=models.ImageField(blank=True, upload_to='photos/%Y/%m/%d'),
        ),
    ]
