# Generated by Django 4.0.4 on 2022-05-26 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carnets', '0007_carnet_photo_1'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calvac',
            name='observations',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
